/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiNewsletter from "@strapi-newsletter/strapi/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiGoogleAuth from "strapi-google-auth/strapi-admin";
import customLinks from "strapi-plugin-custom-links/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-newsletter": strapiNewsletter,
    "color-picker": colorPicker,
    documentation: documentation,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "strapi-google-auth": strapiGoogleAuth,
    "custom-links": customLinks,
    navigation: navigation,
  },
});
