version: '3'
services:
  app:
    build: .
    ports:
      - "3000:80"  # El puerto 80 del contenedor se enlaza al puerto 3000 de tu máquina
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    environment:
      - NODE_ENV=development
